# Generated by Django 3.2.13 on 2022-04-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('news_decription', models.TextField(max_length=50000)),
                ('news_video', models.CharField(max_length=1000)),
                ('news_audio', models.CharField(max_length=1000)),
                ('news_image', models.CharField(max_length=1000)),
                ('news_author', models.CharField(max_length=200)),
            ],
        ),
    ]
